-- NOT LIKE
SELECT DISTINCT CITY
FROM STATION
WHERE CITY NOT LIKE '%A' 
  AND CITY NOT LIKE '%E'
  AND CITY NOT LIKE '%I'
  AND CITY NOT LIKE '%O'
  AND CITY NOT LIKE '%U'
;

-- RIGHT, NOT IN
SELECT DISTINCT CITY
FROM STATION
WHERE RIGHT(CITY, 1) NOT IN ('A', 'E', 'I', 'O', 'U')
;