-- WHERE 서브쿼리 
SELECT ROUND(LONG_W, 4)
FROM STATION
WHERE LAT_N = (SELECT MIN(LAT_N)
               FROM STATION
               WHERE LAT_N > 38.7780)
;

-- 서브쿼리 없이 (ORDER BY, LIMIT)
SELECT ROUND(LONG_W, 4)
FROM STATION
WHERE LAT_N > 38.7780 
ORDER BY LAT_N
LIMIT 1
;